@startmindmap
* Programacao Orientada a Objetos em Java
** Plataforma Java
*** Java Virtual Machine (JVM)
*** Java Runtime Environment (JRE)
*** Java Develoment Kit (JDK)
**** jshell
*****_ ambiente de aprendizado e teste REPL (Read-Eval-Print-Loop)
**** javac
*****_ compilador de programas java
**** java
*****_ executa programas java
*****_ public static void main(String[] args){}
** Elementos básicos da linguagem
*** literais (valores)
****_ números: inteiro e ponto-flutuante (decimal)
****_ caractere: 'a'
****_ boolean: true false
****_ String: "a"
*** identifiers
****_ nomeiam variáveis, classes, métodos etc
*** separators
****_ {} [] () ; , ... @
*** keywords (palavras reservadas)
*** operadores
**** associação
*****_ =
**** aritiméticos
*****_ +, -, *, /, %
*****_ ++, --
**** relacionais
*****_ < > <= >=d
**** lógicos
*****_ &&, &
*****_ ||, |, ^
*****_ !, ==
**** bitwise
*** tipos
**** tipos primitivos
*****_ byte (8 bits): -127 a 128
*****_ short (16 bits): 
*****_ int (32 bits):
*****_ long (64 bits):
*****_ float
*****_ double
*****_ caractere: 'a'
*****_ boolean: true ou false
**** tipos complexos (reference types)
*****:classe
<code>
public class Aluno {...}
</code>;
*****:interface
<code>
public interface Bolsita {...}
</code>;
*** variáveis
****_ tipo identificador;
****_ tipo identificador = valor_inicial;
** Estruturas de controle
*** estruturas de seleção
****_ if (condition) {statements}
****_ if (condition) {statements} else {statements}
****_ if (condition) {statements} else if (condition) {statements;} else {statements;}
****_ switch (selector) { case : statements; break; default: statements; break;}
****_ switch (selector) { case -> statement; default -> statements;}
*** estruturas de iteração
****_ do {statements} while (condition)
****_ while (condition) {statements}
****_ for (counter; condition; increment) {statements}
****_ for (type element : expression) {statements}
-- Orientacao a Objetos
--- Classes e objetos
----_ dados (atributos)
----_ comportamentos (métodos)
--- Abstração
--- Encapsulamento
--- Herança
--- Polimorfismo
--- Interfaces
--- Classes abstratas
--- Sobrecarga
--- Sobrescrita
--- Modificadores de acesso
--- Pacotes e modularizacao
-- Coleções de elementos
--- Array
----_ int[] i; int[] i = new int[5]; int[] i = {1, 2, 3}
----_ int[][] i; int[][] i = new int[5][4]; int[][] i = {{1, 2}, {3, 4}, {5, 6}}
---- java.lang.Arrays
-----_ sort
-----_ compare
-----_ copyOf
-----_ fill
-----_ binarySearch
-----_ toString
-----_ ...
--- Framework Collections
---- ArrayList
-----_ ArrayList<String> a = new ArrayList<>();
----- java.lang.Collections
------_ binarySearch
------_ fill
------_ reverseOrder
------_ shuffle
------_ sort
-- Tratamento de excecoes
---_ try {statements} catch (Exception e) {statements}
---_ try {statements} catch (ArrayIndexOutOfBoundsException e) {statements} catch (Exception e) {statements}
---_ try {statements} catch (ArrayIndexOutOfBoundsException a | Exception e) {statements}
@endmindmap
