@startuml
skinparam classAttributeIconSize 0


package "java.io" {

    abstract class InputStream
    abstract class OutputStream
    abstract class Reader
    abstract class Writer

    class FilterInputStream extends InputStream
    class FilterOutputStream extends OutputStream
    class InputStreamReader extends Reader
    class OutputStreamWriter extends Writer
    class File
    class FileInputStream extends InputStream
    class FileOutputStream extends OutputStream
    class FileReader extends InputStreamReader
    class FileWriter extends OutputStreamWriter
    class BufferedInputStream extends FilterInputStream
    class BufferedOutputStream extends FilterOutputStream
    class BufferedReader extends Reader
    class BufferedWriter extends Writer
}

package "java.nio.file" {
    interface Path
    class Paths
    class Files
    interface DirectoryStream
    interface FileSystem
    class FileSystems
}

@enduml
